In [ ]:
# with open('./drive/MyDrive/readME.md','w') as f:
#     daa = f.write('*반가워요.')
#     print('저장되었습니다.')
# !pwd

In [130]:
# 넘파이 버전 확인
import numpy as np
print(np.__version__)

1.26.4


##넘파이(numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

### 1차원과 속성들

In [1]:
# pip  install numpy
import numpy as np
narry= np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[3])
print(narry[2:4])   # <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [18]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b'])   # 타입을 정하지 않으면 문자로 처리
narr3 = np.array([1,2,3,4],dtype='str')
# narr3 = np.array([1,2,'a','b'],dtype='int') / ValueError: invalid literal for int() with base 10: 'a'
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [73]:
narr4 = np.zeros(10,dtype='int64')
narr5 = np.zeros(2)
narr6 = np.zeros((2,2))
narr7 = np.full((3,3),3)
narr8 = np.ones((2,2))
narr9 = np.full((3,3),'number')
narr10 = np.eye(3)
narr11 = np.linspace(1,100,5,endpoint=False,dtype='int64')
narr12 = np.arange(1,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print("="*30)
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print("="*30)
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print("="*30)
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print("="*30)
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print("="*30)
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print("="*30)
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))
print("="*30)
print(narr11,narr11.ndim,narr11.dtype,narr11.shape,narr11.size,type(narr11))
print("="*30)
print(narr12,narr12.ndim,narr12.dtype,narr12.shape,narr12.size,type(narr12))

[0 0 0 0 0 0 0 0 0 0] 1 int64 (10,) 10 <class 'numpy.ndarray'>
[0. 0.] 1 float64 (2,) 2 <class 'numpy.ndarray'>
[[0. 0.]
 [0. 0.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 1 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 1 21 41 61 81] 1 int64 (5,) 5 <class 'numpy.ndarray'>


### 2차원 배열

In [46]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape,arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [54]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim,'/ 데이터타입:',arr2.dtype,'/ 형태:', arr2.shape,'/ 크기:', arr2.size, type(arr2))
print('차원:',arr3.ndim,'/ 데이터타입:',arr3.dtype,'/ 형태:', arr3.shape,'/ 크기:', arr3.size, type(arr3))
print('차원:',arr4.ndim,'/ 데이터타입:',arr4.dtype,'/ 형태:', arr4.shape,'/ 크기:', arr4.size, type(arr4))
print('차원:',arr5.ndim,'/ 데이터타입:',arr5.dtype,'/ 형태:', arr5.shape,'/ 크기:', arr5.size, type(arr5))
print('차원:',arr6.ndim,'/ 데이터타입:',arr6.dtype,'/ 형태:', arr6.shape,'/ 크기:', arr6.size, type(arr6))

차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 <class 'numpy.ndarray'>
차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 <class 'numpy.ndarray'>
차원: 2 / 데이터타입: int64 / 형태: (2, 5) / 크기: 10 <class 'numpy.ndarray'>
차원: 2 / 데이터타입: int64 / 형태: (5, 2) / 크기: 10 <class 'numpy.ndarray'>
차원: 3 / 데이터타입: int64 / 형태: (3, 3, 3) / 크기: 27 <class 'numpy.ndarray'>


In [100]:
a1 = np.arange(1,22).reshape(3,7)
a2 = np.arange(1,8).reshape(7,1)
a3 = np.arange(1,11).reshape(5,2)
a4 = np.arange(1,22).reshape(3,7)
a5 = np.arange(1,13).reshape(4,3,1)
print(a1)
print("="*25)
print(a2)
print("="*25)
print(a3)
print("="*25)
print(a4)
print("="*25)
print(a5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [86]:
print(a1)
print("="*25)
print(a1[1])
print("="*25)
print(a1[1][2:5])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[ 8  9 10 11 12 13 14]
[10 11 12]


In [95]:
print(a4)
print("="*25)
print(a4[0][3:])
print("="*25)
print(a4[1][3:])
print("="*25)
print(a4[2][3:])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [109]:
print(a4[1:3,2:4])
print("="*25)
print(a4[1:3,4:6])
print("="*25)
print(a4 % 2 == 0)

[[10 11]
 [17 18]]
[[12 13]
 [19 20]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [108]:
print([a4>12])
print("="*40)
print(a4[a4>12])

[array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])]
[13 14 15 16 17 18 19 20 21]


In [111]:
# np 배열 연산 // shape 가 같을 경우 원소별 연산이 가
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print("덧셈:",np1+np2)
print("뺄셈:",np1-np2)
print("곱셈:",np1*np2)
print("나눗셈:",np1/np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [-5 -5 -5 -5 -5]
곱셈: [ 6 14 24 36 50]
나눗셈: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [112]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[11 12 13 14 15]


In [129]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
print(br1)
print("-"*15)
print(br2)
# 스칼라와 연산
print('==스칼라와 연산==')
print(br1+3)
print("-"*15)
print(br1*2)
# 2D와 1D의 연산
print('==2D와 1D의 연산==')
print(br1+br2)
print("-"*15)
print(br1*br2)
print("-"*15)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[11 22 33]
==스칼라와 연산==
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
==2D와 1D의 연산==
[[12 24 36]
 [15 27 39]
 [18 30 42]]
---------------
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]
---------------


In [135]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print("-"*20)
print(ff.reshape(1,9))
print("-"*20)
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[1 2 3 4 5 6 7 8 9]]
--------------------
[1 2 3 4 5 6 7 8 9]


### Random number 발생

- np.random.randint(): 균일 분포의 정수 난수
- np.random.rand() : 0부터 1사이의 균일 분포 난수 생성
- np.random.randn() : 표준 정규 분포 난수 생성
- np.random.normal() : 정규 분포 난수 생성

In [3]:
# randomint
import numpy as np
x = np.random.randint(0,255,size=(3,3,3))
x

array([[[100,  35, 183],
        [154, 141,  70],
        [119, 122, 193]],

       [[149,  73, 199],
        [163, 225, 146],
        [169,  40,   2]],

       [[ 62,  94,  51],
        [183, 133, 208],
        [ 69,  70,  43]]], dtype=int32)

In [4]:
print('평균값:',np.mean(x),'표준편차:',np.std(x),'최소값:',x.min(),'최대값:',x.max())

평균값: 118.37037037037037 표준편차: 60.31776849452508 최소값: 2 최대값: 225


In [7]:
x = np.random.rand(10,5)
x

array([[0.62662939, 0.63456548, 0.36578547, 0.8284279 , 0.376012  ],
       [0.9584872 , 0.56483852, 0.1669839 , 0.09942657, 0.47721089],
       [0.03790656, 0.40693875, 0.79246406, 0.04967547, 0.7747701 ],
       [0.43132136, 0.24551039, 0.85691023, 0.13818895, 0.04915144],
       [0.62471232, 0.60339285, 0.54494539, 0.13594066, 0.49365014],
       [0.04162221, 0.28074172, 0.87680059, 0.82183809, 0.74935773],
       [0.00807906, 0.8237454 , 0.39983288, 0.01641275, 0.82429031],
       [0.07572146, 0.14350335, 0.68265425, 0.14883875, 0.3279443 ],
       [0.22027777, 0.11817574, 0.84474039, 0.24688558, 0.09984174],
       [0.03175818, 0.53930918, 0.7225677 , 0.10486154, 0.08177567]])

In [8]:
x = np.random.randint(1,5,size=(10,5))
x

array([[3, 2, 1, 3, 2],
       [2, 2, 2, 1, 1],
       [2, 3, 1, 4, 1],
       [3, 3, 3, 4, 4],
       [1, 3, 2, 4, 1],
       [4, 1, 4, 4, 4],
       [4, 1, 3, 2, 2],
       [1, 4, 2, 3, 4],
       [2, 3, 1, 1, 4],
       [4, 4, 3, 1, 2]], dtype=int32)

In [8]:
size = (10,5)
x = np.random.randint(1,5,size=size)
x

array([[1, 1, 4, 4, 4],
       [1, 1, 2, 4, 1],
       [3, 4, 3, 1, 3],
       [3, 2, 4, 4, 3],
       [2, 1, 3, 4, 2],
       [2, 4, 1, 1, 1],
       [2, 4, 2, 1, 2],
       [2, 4, 1, 3, 2],
       [4, 1, 4, 4, 4],
       [1, 1, 2, 4, 3]], dtype=int32)

In [14]:
x = np.random.normal(5,3,(10,5))  # 평균 5, 표준편차 3
print(x)
print(np.mean(x),np.std(x),x.min(),x.max())

[[ 9.42587359  4.87055903 10.7619221   2.85903449  5.92049427]
 [ 4.7198386   8.36020644  4.71415065  7.17434844  2.66539416]
 [ 5.97300116  6.99681822  5.0194435   3.57156512  5.03524082]
 [ 3.0084866   5.79586838  4.66455387  6.75991498  1.63356915]
 [ 5.99750262  4.00705508 10.66329323  4.01062357  9.34080148]
 [ 8.59511581  7.71095037  4.27166526  4.27864311  3.69465079]
 [ 5.35062187  7.25805686  3.37587805  1.61568323  4.15629356]
 [ 1.49336668  7.74252331  8.86994782  3.91562741  5.45734386]
 [ 2.25925572  2.55532906  5.03372256  6.99468022  6.47501351]
 [10.05507143 -0.53352254  4.77539274  4.18446887  0.13599921]]
5.273426766153205 2.5905415601509496 -0.5335225357475437 10.761922101489414


- 분산(Variance) : 데이터 값들이 평균으로부터 얼마나 멀리 떨어져 있는지를 측정하여, 데이터의 변동성을 평가
- 표준편차(Standard Deviation) : 데이터가 평균을 중심으로 얼마나 분포되어 있는지를 나타내는 통계적 척도입니다. 분산의 제곱근으로 정의되며, 데이터 값들이 평균으로부터 얼마나 떨어져 있는지에 대한 정보를 제공

In [16]:
x = np.random.randn(10,5)
print(x) 
print(np.mean, np.std(x), x.min(), x.max())

[[ 0.24668178  0.90364791  0.67398814 -0.96270447  2.09626579]
 [ 0.48469512 -0.82948897  0.63604178  0.75278525  1.35048902]
 [ 1.15670195  0.66184567  0.42436425  0.16006534 -0.66965752]
 [ 1.044257   -0.30163675 -0.62947989 -0.80546212 -0.7646682 ]
 [ 0.97611865  0.9075325   0.23867711 -1.83141256 -0.63063301]
 [-0.16878259 -0.83026125 -1.59025587 -1.35566888 -1.21306561]
 [ 0.47781874  0.16137101 -0.83968685 -0.71109981  0.04548814]
 [ 0.01733655  0.64407409  1.64543276  1.00019011 -0.09207315]
 [ 0.02423063  0.86440423 -0.2969552  -0.29013229 -0.25291004]
 [-0.92298212 -0.11796041 -0.69012926  0.00684399  0.27244639]]
<function mean at 0x000001C30A087740> 0.8453322753371428 -1.8314125586177075 2.0962657858958993


In [22]:
x = np.array([3,0,434,5,2,0,23,5,3,4,98,0])
print('x의 개수', len(x))
print('x의 개수', np.count_nonzero(x))
print('0의 개수', len(x) - np.count_nonzero(x))

print('x의 평균', np.mean(x))
print('x의 평균', x.mean())

print('x의 분산', np.var(x))
print('x의 분산', x.var())

print('x의 표준편차', np.std(x))
print('x의 표준편차', x.std())

print('x의 최댓값', x.max())
print('x의 최솟값', x.min())
print('x의 중앙값', np.median(x))

x의 개수 12
x의 개수 9
0의 개수 3
x의 평균 48.083333333333336
x의 평균 48.083333333333336
x의 분산 14236.07638888889
x의 분산 14236.07638888889
x의 표준편차 119.31503002090261
x의 표준편차 119.31503002090261
x의 최댓값 434
x의 최솟값 0
x의 중앙값 3.5


In [23]:
print(np.percentile(x,0))  # 최소값
print(np.percentile(x,25))  # 제1사분위수
print(np.percentile(x,50))  # 중앙값, 제2사분위쉬
print(np.percentile(x,75))  # 제3사분위수
print(np.percentile(x,100))  # 최대값

0.0
1.5
3.5
9.5
434.0


In [5]:
print(len(x.flatten()))

27


In [6]:
y = np.array([0,1,2,3,4,6,34,2,0,23,3,1,2,3,0,0,12,3,5,34,3,3,23,0,1,2,3]).reshape(3,3,3)
print(len(y.flatten()))
print(np.count_nonzero(y))

27
22


### 판다스(pandas)

- 시리즈(series)
- 데이터프레임(dataframe)

In [4]:
# !pip install pandas

In [2]:
import numpy as np
import pandas as pd

In [6]:
# 판다스 기초,
data1 = np.arange(1,11)
print(data1)
data2 = pd.Series(data1)
print(data2, type(data2), data2.index, data2.values, data2.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64 <class 'pandas.core.series.Series'> RangeIndex(start=0, stop=10, step=1) [ 1  2  3  4  5  6  7  8  9 10] int64


In [7]:
# 판다스 시리즈의 데이터타입
data3 = pd.Series([1,2,3,4,5]) #, dtype="flat")
print(data3)

0    1
1    2
2    3
3    4
4    5
dtype: int64


In [10]:
# 판다스 시리즈의 인덱스설정
data3 = pd.Series([1,2,3,4], index=['a','b','c','d'])
print(data3)

a    1
b    2
c    3
d    4
dtype: int64


In [21]:
# 판다스 시리즈 딕셔너리데이터
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa':32976
}
# population_dict.keys()
# population_dict.values()
# population_dict.items()
country = pd.Series(population_dict)
print(country, country.index, country.values)
print(country.ndim, country.shape, country.size)
# 시리즈 원소에 접근방법
print(country['korea'])
print(country.loc['japan'])
print(country.iloc[2])  # iloc 없이 숫자로 인덱싱은 불가

korea      5182
japan     12622
china    141178
usa       32976
dtype: int64 Index(['korea', 'japan', 'china', 'usa'], dtype='object') [  5182  12622 141178  32976]
1 (4,) 4
5182
12622
141178


In [32]:
# 판다스 데이터 프레임
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9]],index=['a','b','c'],columns=['A','B','C'])
df

A  B  C
a  1  2  3
b  4  5  6
c  7  8  9

In [35]:
# 테스트
import numpy as np
import pandas as pd

# 두 개의 시리즈 데이터
print("인구수 시리즈 데이터:")
population_dict = {
    'korea':5182,
    'japan':12622,
    'china':141178,
    'usa': 32976
}
population = pd.Series(population_dict)
print(population)
print("GDP 시리즈 데이터:")
GDP_dict = {
    'korea':169320000,
    'japan':516700000,
    'china':140925000,
    'usa': 2041280000
}
GDP = pd.Series(GDP_dict)
print(GDP)
print('='*25)
print("데이터 프레임 생성")
country = pd.DataFrame({'population':population,'gdp':GDP})
country.index.name = "Country"  # 인덱스 이름 지정
country.columns.name = "Info"  # 컬럼 이름 지정
print(country.index, country.columns)
print(country.values, country.shape, country.size, country.ndim)

인구수 시리즈 데이터:
korea      5182
japan     12622
china    141178
usa       32976
dtype: int64
GDP 시리즈 데이터:
korea     169320000
japan     516700000
china     140925000
usa      2041280000
dtype: int64
데이터 프레임 생성
Index(['korea', 'japan', 'china', 'usa'], dtype='object', name='Country') Index(['population', 'gdp'], dtype='object', name='Info')
[[      5182  169320000]
 [     12622  516700000]
 [    141178  140925000]
 [     32976 2041280000]] (4, 2) 8 2


In [45]:
country
# country.loc['korea':]과 출력이 같음

Info     population         gdp
Country                        
korea          5182   169320000
japan         12622   516700000
china        141178   140925000
usa           32976  2041280000

In [47]:
country.loc['korea':'japan']

Info     population        gdp
Country                       
korea          5182  169320000
japan         12622  516700000

In [46]:
country.loc['korea':'japan',:'population']  # 끝자리 포함해서 출력됨

Info     population
Country            
korea          5182
japan         12622

In [40]:
# 데이터 프레임의 요소 접근 방법 / Loc, iLoc 출력 동일
country.loc['korea'],country.loc['usa']
country.iloc[2],country.iloc[3]

(Info
 population       141178
 gdp           140925000
 Name: china, dtype: int64,
 Info
 population         32976
 gdp           2041280000
 Name: usa, dtype: int64)

In [52]:
country.iloc[0:2]

Info     population        gdp
Country                       
korea          5182  169320000
japan         12622  516700000

In [53]:
country.iloc[0:2,:1]

Info     population
Country            
korea          5182
japan         12622

In [63]:
country.iloc[1:4,1:2]

Info            gdp
Country            
japan     516700000
china     140925000
usa      2041280000

In [64]:
country.loc['japan':'china']

Info     population        gdp
Country                       
japan         12622  516700000
china        141178  140925000

In [66]:
# 컬럼추가
# country['test']=[11,22,33,44]
# country.drop('test',axis=1)
gdpper = country['gdp'] / country['population']
country['gdp_per'] = gdpper
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326

In [67]:
# 행추가 방법1
country.loc['india'] = [142222,150505000,1212121]
country.loc['india','gdp_per'] = country.loc['india','gdp']/country.loc['india','population']
country

Info     population         gdp       gdp_per
Country                                      
korea          5182   169320000  32674.642995
japan         12622   516700000  40936.460149
china        141178   140925000    998.207936
usa           32976  2041280000  61901.989326
india        142222   150505000   1058.239935

In [68]:
# 행추가 방법2
africa = pd.Series( data =[123456,7777777],index=['population','gdp'])
country.loc['africa']=africa
# country.loc['africa','gdp_per'] = country.loc['africa','gdp']/country.loc['africa','population']
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935
africa     123456.0  7.777777e+06           NaN

In [69]:
# 결측값(NaN) 확인
country.isnull()#.sum()

Info     population    gdp  gdp_per
Country                            
korea         False  False    False
japan         False  False    False
china         False  False    False
usa           False  False    False
india         False  False    False
africa        False  False     True

In [70]:
# 열제거 drop( 이름, axis=0 )
country = country.drop('africa', axis=0) # inplace = True
country

Info     population           gdp       gdp_per
Country                                        
korea        5182.0  1.693200e+08  32674.642995
japan       12622.0  5.167000e+08  40936.460149
china      141178.0  1.409250e+08    998.207936
usa         32976.0  2.041280e+09  61901.989326
india      142222.0  1.505050e+08   1058.239935

In [160]:
# 테스트 1 조건
country[country['population'] > 140000]

Info     population          gdp      gdp_per
Country                                      
china      141178.0  140925000.0   998.207936
india      142222.0  150505000.0  1058.239935

In [162]:
# 테스트 2 조건 , 슬라이싱 (loc,iloc 필수)
country[(country['population'] > 10000) & (country['population'] < 100000)].loc[:,:'population']

Info     population
Country            
japan       12622.0
usa         32976.0

In [83]:
df = pd.DataFrame([['홍길동','80','70','80'],['박철수','60','70','80'],['김영희','70','90','80']],index=['0','1','2'],columns=['이름','국어','수학','영어'])
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [97]:
# 문제 1) 데이터 프레임 생성
import numpy as np
import pandas as pd

a_dict = {
    "홍길동":80,
    "박철수":60,
    "김영희":70
}
A = pd.Series(a_dict)

b_dict = {
    "홍길동":70,
    "박철수":70,
    "김영희":90
}
B = pd.Series(b_dict)

c_dict = {
    "홍길동":80,
    "박철수":80,
    "김영희":80
}
C = pd.Series(c_dict)

df = pd.DataFrame({'국어':A, '수학':B, '영어':C}) 
df

국어  수학  영어
홍길동  80  70  80
박철수  60  70  80
김영희  70  90  80

In [99]:
# 문제 2) 박철수의 국어, 수학점수만 출력
df.loc[['박철수'], ['국어', '수학']]

국어  수학
박철수  60  70

In [166]:
# 기본적인 방법
data = {
    '이름':['홍길동','박철수','김영희'],
    '국어':[80,60,70],
    '수학':[70,70,90],
    '영어':[80,80,80]
}
df = pd.DataFrame(data)
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [167]:
# 키값쌍으로 리스트에 저장하는 방법
data = [
    {'이름':'홍길동','국어':80,'수학':70,'영어':80},
    {'이름':'박철수','국어':60,'수학':70,'영어':80},
    {'이름':'김영희','국어':70,'수학':90,'영어':80}]
df = pd.DataFrame(data)
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [215]:
# 리스트에 튜플로 저장하는 방법
data = [
    ('홍길동',80,70,80),
    ('박철수',60,70,80),
    ('김영희',70,90,80)]
df = pd.DataFrame(data, columns=['이름','국어','수학','영어'])
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [221]:
import numpy as np
# data0 = [
#     ('홍길동',80,70,80),
#     ('박철수',60,70,80),
#     ('김영희',70,90,80)]
# data = np.array(data0)
data = np.array([['홍길동',80,70,80],['박철수',60,70,80],['김영희',70,90,80]])
df = pd.DataFrame(data, columns=['이름','국어','수학','영어'])

In [222]:
# 1
df

이름  국어  수학  영어
0  홍길동  80  70  80
1  박철수  60  70  80
2  김영희  70  90  80

In [223]:
# 2
df.loc[1:1]
df.iloc[1:2]

이름  국어  수학  영어
1  박철수  60  70  80

In [224]:
# 3
# print(df['국어'].dtype)
df[df['국어'].astype(int) >=70]

이름  국어  수학  영어
0  홍길동  80  70  80
2  김영희  70  90  80

In [226]:
# 4
df['평균'] = (df['국어'].astype(int) + df['수학'].astype(int) + df['영어'].astype(int))/3
print('평균',df['평균'].dtype)
df.round()

평균 float64


이름  국어  수학  영어    평균
0  홍길동  80  70  80  77.0
1  박철수  60  70  80  70.0
2  김영희  70  90  80  80.0

In [227]:
# 5
df.loc[3] = ('최자바',55,95,70,77)
df

이름  국어  수학  영어         평균
0  홍길동  80  70  80  76.666667
1  박철수  60  70  80  70.000000
2  김영희  70  90  80  80.000000
3  최자바  55  95  70  77.000000

In [ ]:
문제 2
박철수의 국어와, 수학점수만 출력하라
문제 3
국어가 70점 이상인 사람 모든 행을 출력하라
문제 4
모든 과목의 평균점수를 마지막 컬럼에 넣고 "평균" 이라는 이름으로 만들어 넣어라
문제 5
전학온 학생을 추가하라 (최자바 55 95 70)