In [ ]:
# with open('./drive/MyDrive/readME.md','w') as f:
#     daa = f.write('*반가워요.')
#     print('저장되었습니다.')
# !pwd

In [130]:
# 넘파이 버전 확인
import numpy as np
print(np.__version__)

1.26.4


##넘파이(numpy)

- ndim : 축의 개수
- shape : 배열의 차원정보
- size : 배열안에 있는 원소의 총 개수
- dtype : 배열 원소의 자료형

### 1차원과 속성들

In [1]:
# pip  install numpy
import numpy as np
narry= np.array(range(5))
print(narry,type(narry))
print(narry.ndim)
print(narry.shape)
print(narry.size)
print(narry.dtype)
print(narry[3])
print(narry[2:4])   # <= x <

[0 1 2 3 4] <class 'numpy.ndarray'>
1
(5,)
5
int64
3
[2 3]


In [18]:
narr1 = np.array([1,2,3,4])
narr2 = np.array([1,2,'a','b'])   # 타입을 정하지 않으면 문자로 처리
narr3 = np.array([1,2,3,4],dtype='str')
# narr3 = np.array([1,2,'a','b'],dtype='int') / ValueError: invalid literal for int() with base 10: 'a'
print(narr1,narr1.dtype)
print(narr2,narr2.dtype)
print(narr3,narr3.dtype)

[1 2 3 4] int64
['1' '2' 'a' 'b'] <U21
['1' '2' '3' '4'] <U1


In [73]:
narr4 = np.zeros(10,dtype='int64')
narr5 = np.zeros(2)
narr6 = np.zeros((2,2))
narr7 = np.full((3,3),3)
narr8 = np.ones((2,2))
narr9 = np.full((3,3),'number')
narr10 = np.eye(3)
narr11 = np.linspace(1,100,5,endpoint=False,dtype='int64')
narr12 = np.arange(1,100,20)
print(narr4,narr4.ndim,narr4.dtype,narr4.shape,narr4.size,type(narr4))
print("="*30)
print(narr5,narr5.ndim,narr5.dtype,narr5.shape,narr5.size,type(narr5))
print("="*30)
print(narr6,narr6.ndim,narr6.dtype,narr6.shape,narr6.size,type(narr6))
print("="*30)
print(narr7,narr7.ndim,narr7.dtype,narr7.shape,narr7.size,type(narr7))
print("="*30)
print(narr8,narr8.ndim,narr8.dtype,narr8.shape,narr8.size,type(narr8))
print("="*30)
print(narr9,narr9.ndim,narr9.dtype,narr9.shape,narr9.size,type(narr9))
print("="*30)
print(narr10,narr10.ndim,narr10.dtype,narr10.shape,narr10.size,type(narr10))
print("="*30)
print(narr11,narr11.ndim,narr11.dtype,narr11.shape,narr11.size,type(narr11))
print("="*30)
print(narr12,narr12.ndim,narr12.dtype,narr12.shape,narr12.size,type(narr12))

[0 0 0 0 0 0 0 0 0 0] 1 int64 (10,) 10 <class 'numpy.ndarray'>
[0. 0.] 1 float64 (2,) 2 <class 'numpy.ndarray'>
[[0. 0.]
 [0. 0.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[[3 3 3]
 [3 3 3]
 [3 3 3]] 2 int64 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 1.]
 [1. 1.]] 2 float64 (2, 2) 4 <class 'numpy.ndarray'>
[['number' 'number' 'number']
 ['number' 'number' 'number']
 ['number' 'number' 'number']] 2 <U6 (3, 3) 9 <class 'numpy.ndarray'>
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 2 float64 (3, 3) 9 <class 'numpy.ndarray'>
[ 1 20 40 60 80] 1 int64 (5,) 5 <class 'numpy.ndarray'>
[ 1 21 41 61 81] 1 int64 (5,) 5 <class 'numpy.ndarray'>


### 2차원 배열

In [46]:
print(list(range(2,10)))
print(np.arange(2,10))
range(10)
np.arange(10)

[2, 3, 4, 5, 6, 7, 8, 9]
[2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
arr1 = np.array([[0,0],[0,0]])
print(arr1,arr1.ndim,arr1.dtype,arr1.shape,arr1.size,type(arr1))

[[0 0]
 [0 0]] 2 int64 (2, 2) 4 <class 'numpy.ndarray'>


In [54]:
arr2 = np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3)
arr3 = np.arange(1,10).reshape(3,3)
arr4 = np.arange(1,11).reshape(2,5)
arr5 = np.arange(1,11).reshape(5,2)
arr6 = np.arange(1,28).reshape(3,3,3)
print('차원:',arr2.ndim,'/ 데이터타입:',arr2.dtype,'/ 형태:', arr2.shape,'/ 크기:', arr2.size, type(arr2))
print('차원:',arr3.ndim,'/ 데이터타입:',arr3.dtype,'/ 형태:', arr3.shape,'/ 크기:', arr3.size, type(arr3))
print('차원:',arr4.ndim,'/ 데이터타입:',arr4.dtype,'/ 형태:', arr4.shape,'/ 크기:', arr4.size, type(arr4))
print('차원:',arr5.ndim,'/ 데이터타입:',arr5.dtype,'/ 형태:', arr5.shape,'/ 크기:', arr5.size, type(arr5))
print('차원:',arr6.ndim,'/ 데이터타입:',arr6.dtype,'/ 형태:', arr6.shape,'/ 크기:', arr6.size, type(arr6))

차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 <class 'numpy.ndarray'>
차원: 2 / 데이터타입: int64 / 형태: (3, 3) / 크기: 9 <class 'numpy.ndarray'>
차원: 2 / 데이터타입: int64 / 형태: (2, 5) / 크기: 10 <class 'numpy.ndarray'>
차원: 2 / 데이터타입: int64 / 형태: (5, 2) / 크기: 10 <class 'numpy.ndarray'>
차원: 3 / 데이터타입: int64 / 형태: (3, 3, 3) / 크기: 27 <class 'numpy.ndarray'>


In [100]:
a1 = np.arange(1,22).reshape(3,7)
a2 = np.arange(1,8).reshape(7,1)
a3 = np.arange(1,11).reshape(5,2)
a4 = np.arange(1,22).reshape(3,7)
a5 = np.arange(1,13).reshape(4,3,1)
print(a1)
print("="*25)
print(a2)
print("="*25)
print(a3)
print("="*25)
print(a4)
print("="*25)
print(a5)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[[[ 1]
  [ 2]
  [ 3]]

 [[ 4]
  [ 5]
  [ 6]]

 [[ 7]
  [ 8]
  [ 9]]

 [[10]
  [11]
  [12]]]


In [86]:
print(a1)
print("="*25)
print(a1[1])
print("="*25)
print(a1[1][2:5])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[ 8  9 10 11 12 13 14]
[10 11 12]


In [95]:
print(a4)
print("="*25)
print(a4[0][3:])
print("="*25)
print(a4[1][3:])
print("="*25)
print(a4[2][3:])

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21]]
[4 5 6 7]
[11 12 13 14]
[18 19 20 21]


In [109]:
print(a4[1:3,2:4])
print("="*25)
print(a4[1:3,4:6])
print("="*25)
print(a4 % 2 == 0)

[[10 11]
 [17 18]]
[[12 13]
 [19 20]]
[[False  True False  True False  True False]
 [ True False  True False  True False  True]
 [False  True False  True False  True False]]


In [108]:
print([a4>12])
print("="*40)
print(a4[a4>12])

[array([[False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True]])]
[13 14 15 16 17 18 19 20 21]


In [111]:
# np 배열 연산 // shape 가 같을 경우 원소별 연산이 가
np1 = np.array([1,2,3,4,5])
np2 = np.array([6,7,8,9,10])
print("덧셈:",np1+np2)
print("뺄셈:",np1-np2)
print("곱셈:",np1*np2)
print("나눗셈:",np1/np2)

덧셈: [ 7  9 11 13 15]
뺄셈: [-5 -5 -5 -5 -5]
곱셈: [ 6 14 24 36 50]
나눗셈: [0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [112]:
# 브로드캐스팅
np3 = np1 + 10
print(np3)

[11 12 13 14 15]


In [129]:
br1 = np.arange(1,10).reshape(3,3)
br2 = np.array([11,22,33])
print(br1)
print("-"*15)
print(br2)
# 스칼라와 연산
print('==스칼라와 연산==')
print(br1+3)
print("-"*15)
print(br1*2)
# 2D와 1D의 연산
print('==2D와 1D의 연산==')
print(br1+br2)
print("-"*15)
print(br1*br2)
print("-"*15)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------------
[11 22 33]
==스칼라와 연산==
[[ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
---------------
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
==2D와 1D의 연산==
[[12 24 36]
 [15 27 39]
 [18 30 42]]
---------------
[[ 11  44  99]
 [ 44 110 198]
 [ 77 176 297]]
---------------


In [135]:
ff = np.arange(1,10).reshape(3,3)
print(ff)
print("-"*20)
print(ff.reshape(1,9))
print("-"*20)
print(ff.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
--------------------
[[1 2 3 4 5 6 7 8 9]]
--------------------
[1 2 3 4 5 6 7 8 9]
